### ISSUE TITLE
Workshop without adress cannot be published

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#10]
I encounter an issue…Murai Céamique is a member, she offers pottery workshops but she does not want to publish her address. So it says the it is in Wakefield and the address will be communicated with the inscription confirmation. Hum…Since a place is mandatory, could we entered only a city and postal code? I have to admit that I disn’t anticipate this one.  Here workshop is in draft: Ateliers d’introduction.

**Comment by troughc** [comment]
@IPlouffe the solutin for this one is in progress. We are making the street address optional (not a mandatory field)

**Comment by troughc** [comment]
@IPlouffe you can now publish places without a street address.
