### ISSUE TITLE
Bug filters

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#105]
I selected brouillon, then selected the user  avilledelaval, but the brouillon from other users are still there... 
![Capture d’écran, le 2024-12-12 à 12 44 30](https://github.com/user-attachments/assets/3300bbc8-96eb-436e-b3ad-f105174e6220)

**Comment by AbhishekPAnil** [comment]
This has been fixed with the above PR .
Tested in production:PASSED.

**Comment by troughc** [comment]
@MaudeFJ this was a side effect bug that was caused by another issue we were working on. It's fixed now. Have a great day!
