### ISSUE TITLE
Display [parent term - child term] in pill for hierarchical taxonomies

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#11]
Feature Enhancement to displaying selected terms from controlled vocabulary drop-downs: display the immediate parent term with a child term when selected in fields like Event type as follows [parent term - selected child term]

Example from Tout Culture Event types list: 
- if "Dance", a child term of "Performance",  is selected, display, "Performance - Dance". 
- - If "Dance", a child term of "Workshop" is selected, display "Workshop - Dance"
NOTE: Do not change how the dropdown list displays options. That is good as is.

Reason for the enhancement:
Some taxonomies include terms grouped in hierarchies; and some subcategory terms (the children of a parent term) are used for different parent terms. For example, see the Tout Culture Event types (and see example above). 
In cases where the term appears in multiple categories, the user cannot differentiate what they chose without displaying the parent term. 

Screenshot example of current implementation - this example shows "Danse" selected twice, once from under "Atelier" and once from under "Spectacle". You cannot tell which is which
<img width="487" alt="Screenshot 2023-07-18 at 2 13 48 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/9c734eda-09a4-4805-bd95-725c2558c0c0">

Adding the parent name to the tag will clarify the choice and inform any user who looks at this event in the CMS.

Original feedback from Tout Culture:
_Something does not feel right. In the Taxonomy, I added the concept « Ateliers ». Since there are different type of workshop, I added « arts visuels » and « métiers d'art » as a sub-catégorie of worshop. Now the event is still showing in the list of events. Plus it doesn't say that it is a workshop. It just says : Métiers d'art.  How will Minimal will tel if it is an event or a workshop?_

**Comment by troughc** [comment]
@saumier can we discuss this one tomorrow please.

**Comment by troughc** [comment]
@saumier can you please check into this issue with Event Types - differentiating between a DANCE workshop and a DANCE performance if the user only selects DANCE (second level in the hierarchy). 
Is there any issue with this that needs to be addressed in the open API?

**Comment by troughc** [comment]
@IPlouffe the API that we are providing to MINIMAL includes the PARENT information about a subcategory (like Danse). For example, the Danse parent is atelier: - this information is provided via the API.  
@IPlouffe I have updated this issue to tackle a CMS display issue (as a future enhancement). In terms of MINIMAL displaying what you need, there should be no issue. Let me know if that is correct. Thanks!

**Comment by troughc** [comment]
Here is a screenshot example of what it would look like.


![Image](https://github.com/culturecreates/tech-support-tickets/assets/64489312/0db8af1b-a148-41bf-bd77-f2fec94e66d4)

**Comment by IPlouffe** [comment]
It looks great! It’s clear.

***@***.***<http://www.cultureoutaouais.org/>
Isabelle Plouffe
Gestionnaire de projets

819 595-2601, poste 227
1 855 595-2601

cultureoutaouais.org<http://www.cultureoutaouais.org/>


[Titre : Facebook  - Description : Icône Facebook]<https://www.facebook.com/cultureoutaouais07>     [Titre : instagram - Description : icône Instagram] <https://www.instagram.com/culture_outaouais/?hl=fr>      [Titre : LinkedIn - Description : Icône LinkedIn] <https://ca.linkedin.com/company/culture-outaouais>      [Titre : Twitter - Description : Icône Twitter] <https://twitter.com/culture07>

[Une image contenant texte  Description générée automatiquement]<http://www.touculture.ca/>

De : troughc ***@***.***>
Envoyé : 3 août 2023 11:06
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Isabelle Plouffe ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Display [parent term - child term] in pill for hierarchical taxonomies (Issue #11)


Here is a screenshot example of what it would look like.

[Image]<https://user-images.githubusercontent.com/64489312/258154257-0db8af1b-a148-41bf-bd77-f2fec94e66d4.png>

**Comment by troughc** [comment]
@AbhishekPAnil fyi, here is a link to the figma: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=6869-127868&mode=dev

**Comment by AbhishekPAnil** [comment]
The enhancement is updated in staging. @troughc Please check it out and let me know if any changes are required.Thanks

Added closes tag to commit [6dd6144](https://github.com/culturecreates/footlight-app/pull/768/commits/6dd6144f911c2360fd3d57a85de9658b17a77b0c)

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
