### ISSUE TITLE
Multiple dates event

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#12]
When I select multiple day event  with personnalized frequency, It doesn't let me choose multiple single days. I have to enter a période and then delete and add the one I want. I would like to be able to directly select the days I want.

**Comment by troughc** [comment]
@IPlouffe you can do this actually. Here are the steps:
1. Select Plusiers Dates in the dates section
2. Select Personnalise from the frequence dropdown.
3. Click the Éditer button. 
4. Click on the dates you want to add in the calendar half of the module.

Hope this helps.
