### ISSUE TITLE
Week day and date

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#13]
I would like to be able to see the weekday beside the dates I have selected.

**Comment by troughc** [comment]
@IPlouffe if you mean in the edit dialog (see screenshot), then yes, this is coming soon. If you don't mean in this part of the UI, please let me know.
<img width="669" alt="Screenshot 2023-06-13 at 10 56 06 AM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/7af545ce-e68e-42c7-8cc1-55c5f4f5a8fd">

**Comment by troughc** [comment]
@IPlouffe this issue is now fixed. When you go into the edit dialog, you will always see: 
- the year you are in on the left 
- the names of the days of the week with the dates on the right.
I will now close this issue.

**Comment by troughc** [comment]
@IPlouffe we had to revert the year because it caused the calendar to scroll to the top. However the rest of this issue is implemnted
