### ISSUE TITLE
New CMS: location (Place lookup) doesn't find a place with an apostrophe in the name.

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#14]
Comment from @IPlouffe : When I want to enter L'Avant-Première in « location » it doesn't show up when I enter L'. If I ask for Avant ... it appears.

I retested this and have the same issue in the search field for Location (and probably other search fields). I believe it is because the system is looking for a specific apostrophe ('). Can you fix this so it accepts any apostrophe?

**Comment by troughc** [comment]
@AbhishekPAnil can you estimate how long this would take to fix?
@saumier, after that, we can assign this to a cms iteration.

**Comment by AbhishekPAnil** [comment]
@dev-aravind This seems to be a backend change.

**Comment by troughc** [comment]
@saumier I tested this on CHROME - STAGING by entering the following:
Centre d’action
Centre d'action
(2 different apostrophes). Does this suffice as a test? If you think so, please PASS and CLOSE and push to production.
