### ISSUE TITLE
OLD CMS: update to required fields for address of places

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#15]
**One change:**
Change street address from required to optional. This allows certain parks to be added without having a street address, for example Park Gatineau which covers a large region.  

_Side conversation/question for Gregory
@saumier Question: do  these first 3 letters of the postal code help define what appears on the map? 
Question: right now, you can add just the first 3 letters of postal code, see this example: https://toutculture.stagingminimalmtl.com/event-detail/?event=647e26848b11c40064878f23_

**Comment by saumier** [comment]
@troughc It depends on what is passed to the mapping software and how the mapping software interprets what it receives. On Signé Laval they pass the address (street, city, province, postal code)  to Google maps and then hope for the best result.  Another option is to pass longitude and latitude.

**Comment by troughc** [comment]
@saumier would a longitude and latitude point be able to display a region as it does in the above example? I'm really curious about how a mapping software can show a region. Would the first 3 letters in a postal code be able to provide enough information to do this (since the first 3 letters can cover a specific area of a town, region, etc)? Hoping you know the answer to this.

**Comment by troughc** [comment]
@dev-aravind assigning this to you to implement the change to mandatory fields in the old cms (Places). If it is not you, kindly reassign to the correct person, thank you!

**Comment by saumier** [comment]
> @saumier would a longitude and latitude point be able to display a region as it does in the above example? I'm really curious about how a mapping software can show a region. Would the first 3 letters in a postal code be able to provide enough information to do this (since the first 3 letters can cover a specific area of a town, region, etc)? Hoping you know the answer to this.

I don't have the answer. Longitude and latitude are points. So a map can display the point in the center and the region around more or less.   Google maps sometimes decides to show a boundary around a region, but I don't know what triggers that.

**Comment by saumier** [comment]
@AbhishekPAnil Please go ahead and remove the validation for street address in both en and fr. It should be possible to submit the address to the backend without a street address.
