### ISSUE TITLE
change email address for tout culture contact

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#16]
The current email address used in email communications for tout culture contact is [support@cultureoutaouais.com](mailto:support@cultureoutaouais.com).

Please change this to: [toutculture@cultureoutaouais.org](mailto:toutculture@cultureoutaouais.org).

**Comment by saumier** [comment]
@troughc Please sign in as admin@culturecreates.com and click "Calendars" and then edit the Contacts email.

![Image](https://github.com/culturecreates/tech-support-tickets/assets/419491/5d990890-6175-434b-a359-012417492930)

**Comment by troughc** [comment]
email updated: DONE
