### ISSUE TITLE
Import from ArtsData for Salle Odyssée et Ville de Gatineau?

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#18]
Is this working now?

**Comment by troughc** [comment]
@IPlouffe as discussed we have salle odyssee working (may need to be adjusted) and Ville de Gatineau will be running in the next week or two. 
cc @saumier

**Comment by saumier** [comment]
@troughc  There has been a first pass of most events loaded for Ville de Gatineau (105 events) and Salle Odyssee (50 events). Event series are still missing blocked by dev needed for minting in Artsdata.  Work continues next week with Kim on Console, Suhail on Aggregator, and Me on Artsdata minting event series.
