### ISSUE TITLE
Event dates - plusieurs dates: Enhancement to user workflow

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#19]
For the user case scenario whenre there is 6 differents dates for a show. We select Frequence « personnalisé » and then there is a start date and an end date. It would be less confusing  to put only one date and then add another date and so on so forth. Otherwise we ended up to write the firt date and the last date and then it sélect all the date in between which I dont want.

**Comment by troughc** [comment]
@IPlouffe you can get around this by clicking 'editer' right away (don't enter any dates at all). This button "editer" appears as soon as you choose custom/ personnalisé.

**Comment by troughc** [comment]
@IPlouffe I am closing this issue. Reminder - choose custom/ personnalisé, then open the custom/ personnalisé dialog by clicking editer; then add your dates and times.
