### ISSUE TITLE
Custom dialog - module scrolls up after each time I add a date. 

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#21]
When I add more date to an event, each time the calendar scroll up. It is annoying since when I add date, it will always be afeter the previous one.

**Comment by troughc** [comment]
@IPlouffe this is now fixed. We did this by removing the years persisting at the top of the right side. This was the feature we implemented last week and it caused this bug. (as part of issue #13)

**Comment by troughc** [comment]
@saumier I moved this issue from no status to Done.
