### ISSUE TITLE
Révision des brouillons en provenance de Artsdata par l'organisateur de l'événement

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#26]
Once we receive the Salle Odyssée et Ville de Gatineau events from Artdata they are in a draft form. Then only admin can edit them and I would like the organisation to be able to edit their ouwn events coming from Artsdata. Ex. Caroline Desrochers from Ville de Gatineau should be able to add info or modify an events imported from Artsdata. Thanks!

**Comment by troughc** [comment]
@IPlouffe we have a workaround for this scenario that you can use until we implement the GROUP feature (see note at end of comment).

The workaround is to give your user the log in information for the GUEST aggregator user profile (ex. you give Caroline Desrochers the log in credentials for the GUEST Ville de Gatineau aggregator). The steps would then be as follows:

1. Caroline logs in to the aggregator profile.
2. Caroline reviews an event and then sends it for review. Once an event is sent for review, the AGGREGATOR can no longer update the event.
_IMPORTANT: To stop the aggregator from updating the event at the next import, Caroline MUST send the event for review (saving isn't enough). If Caroline doesn't send her edited event for review her changes would be overwritten by a new import from the aggregator._
3. Caroline continues editing and sending events for review.
4. Next, you or one of your Editors (maybe Scott) log in to Footlight.
5. You review and publish the Ville de Gatineau events from the aggregator that have been SENT FOR REVIEW.
The event will no longer be updated by the aggregator and will be published on your website.

This would be the same process for Salle Odysee

NOTE: we plan to do the "Group" feature after we complete the CMS. At that point, you would be able to create groups so that different users in the group could edit events created by other users in the group, i.e. an human user could edit an aggregator user (like salle odyssee and ville de gatineau.

**Comment by IPlouffe** [comment]
Ok, We will try this.

***@***.***<http://www.cultureoutaouais.org/>
Isabelle Plouffe
Gestionnaire de projets

819 595-2601, poste 227
1 855 595-2601

cultureoutaouais.org<http://www.cultureoutaouais.org/>


[Titre : Facebook  - Description : Icône Facebook]<https://www.facebook.com/cultureoutaouais07>     [Titre : instagram - Description : icône Instagram] <https://www.instagram.com/culture_outaouais/?hl=fr>      [Titre : LinkedIn - Description : Icône LinkedIn] <https://ca.linkedin.com/company/culture-outaouais>      [Titre : Twitter - Description : Icône Twitter] <https://twitter.com/culture07>

[Une image contenant texte  Description générée automatiquement]<http://www.touculture.ca/>

De : troughc ***@***.***>
Envoyé : 5 juillet 2023 15:58
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Isabelle Plouffe ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Révision des brouillons en provenance de Artsdata par l'organisateur de l'événement (Issue #26)


@IPlouffe<https://github.com/IPlouffe> we have a workaround for this scenario that you can use until we implement the GROUP feature (see note at end of comment).

The workaround is to give your user the log in information for the GUEST aggregator user profile (ex. you give Caroline Desrochers the log in credentials for the GUEST Ville de Gatineau aggregator). The steps would then be as follows:

  1.  Caroline logs in to the aggregator profile.
  2.  Caroline reviews an event and then sends it for review. Once an event is sent for review, the AGGREGATOR can no longer update the event.
IMPORTANT: To stop the aggregator from updating the event at the next import, Caroline MUST send the event for review (saving isn't enough). If Caroline doesn't send her edited event for review her changes would be overwritten by a new import from the aggregator.
  3.  Caroline continues editing and sending events for review.
  4.  Next, you or one of your Editors (maybe Scott) log in to Footlight.
  5.  You review and publish the Ville de Gatineau events from the aggregator that have been SENT FOR REVIEW.
The event will no longer be updated by the aggregator and will be published on your website.

This would be the same process for Salle Odysee

NOTE: we plan to do the "Group" feature after we complete the CMS. At that point, you would be able to create groups so that different users in the group could edit events created by other users in the group, i.e. an human user could edit an aggregator user (like salle odyssee and ville de gatineau.

**Comment by troughc** [comment]
@IPlouffe  great! Let's start this after the next upload (always on Thursdays, i.e. today). 
I will send you the log in credentials tomorrow to share with your partner at each organization. 
Note that they cannot change the password as the aggregator also uses the profile. 
cc @saumier

**Comment by IPlouffe** [comment]
Great! Although we have edited the last upload.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : troughc ***@***.***>
Envoyé : Thursday, July 6, 2023 9:52:26 AM
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Isabelle Plouffe ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Révision des brouillons en provenance de Artsdata par l'organisateur de l'événement (Issue #26)


@IPlouffe<https://github.com/IPlouffe> great! Let's start this after the next upload (always on Thursdays, i.e. today).
I will send you the log in credentials tomorrow to share with your partner at each organization.
Note that they cannot change the password as the aggregator also uses the profile.
cc @saumier<https://github.com/saumier>

**Comment by troughc** [comment]
@IPlouffe We had a power outage in Montreal yesterday, which delayed running the aggregator. Gregory (@saumier ) will be running it again Monday and will send the credentials then. Sorry for the delay!

**Comment by troughc** [comment]
@IPlouffe I shared the login information with you and Scott. I am going to close this issue as we are planning to do the group/teams feature after adding the other workspaces to the CMS (organizations, people, places taxonomies etc). That feature is being tracked elsewhere.

**Comment by IPlouffe** [comment]
Très bien. Merci!

***@***.***<http://www.cultureoutaouais.org/>
Isabelle Plouffe
Gestionnaire de projets

819 595-2601, poste 227
1 855 595-2601

cultureoutaouais.org<http://www.cultureoutaouais.org/>


[Titre : Facebook  - Description : Icône Facebook]<https://www.facebook.com/cultureoutaouais07>     [Titre : instagram - Description : icône Instagram] <https://www.instagram.com/culture_outaouais/?hl=fr>      [Titre : LinkedIn - Description : Icône LinkedIn] <https://ca.linkedin.com/company/culture-outaouais>      [Titre : Twitter - Description : Icône Twitter] <https://twitter.com/culture07>

[Une image contenant texte  Description générée automatiquement]<http://www.touculture.ca/>

De : troughc ***@***.***>
Envoyé : 12 juillet 2023 16:18
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Isabelle Plouffe ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Révision des brouillons en provenance de Artsdata par l'organisateur de l'événement (Issue #26)


@IPlouffe<https://github.com/IPlouffe> I shared the login information with you and Scott. I am going to close this issue as we are planning to do the group/teams feature after adding the other workspaces to the CMS (organizations, people, places taxonomies etc). That feature is being tracked elsewhere.
