### ISSUE TITLE
Enhancement: Feature an event from event list

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#27]
Request to add Featured Events to the right-click menu in the event details page. This is already designed and the design can be found here: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4231-101636&mode=design&t=PAUHqm24V3MFwn0i-4
(top left, above the event list page)

**Comment by suhail-aliyar** [comment]
Add an API to feature events by ids. Please note that this API is authorized for Admins and super admins.

**Comment by dev-aravind** [comment]
@sahalali I've added the API like you mentioned. Let me know if you need any changes.

**Comment by saumier** [comment]
@dev-aravind @sahalali I have a comment on the process.  The column "In Review" is for issues to test in staging by QA team. This issue cannot yet be tested by the QA team until the front end consumes the API. Please don't use this column to hand-off issues to another team member. To hand-off to another team member I propose you place in the "Todo" column and assign the issue to a team member. Let me know if this makes sense. Thx.

**Comment by troughc** [comment]
Tested staging CMS in chrome, looks good! :  PASSED
