### ISSUE TITLE
Enhancement: Add Region taxonomy dropdown to quick create (Places)

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#28]
This is a priority enhancement for Signe Laval
Please find the updated component here: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4513-46640&mode=design&t=DeSXUMilMXG8HslU-4

Note for Abhishek and/or Syam: for all the Quick Create components, we will not display the 'Add full details' button until the Edit pages are done

**Comment by troughc** [comment]
NOTE: @troughc and @saumier  need to discuss the user story for this one.

**Comment by saumier** [comment]
@troughc Lets put this into September or October milestone following our discussion. For now I removed the milestone.

**Comment by AbhishekPAnil** [comment]
Make the address field in Quick create for place mandatory.Remove the required option for region taxonomy in edit screen for place.

**Comment by AbhishekPAnil** [comment]
The UI changes  are updated  in staging :
Added support for regions  taxonomy in quick create place and made the address field  required.

Added closes tag to commit message [43cfa84](https://github.com/culturecreates/footlight-app/pull/685/commits/43cfa843fddedb2670edf0ecd3724d714385af55)

**Comment by troughc** [comment]
Tested in Staging on Chrome: PASSED (including the latitude and longitude).
