### ISSUE TITLE
Add Region to the Place component in events

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#29]

**Comment by MaudeFJ** [comment]
<img width="845" alt="Capture d’écran, le 2023-08-07 à 14 51 13" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/fdb2c2ae-031f-49cb-830c-6de02f0472a4">
exemple :

**Comment by troughc** [comment]
Requested design update

**Comment by troughc** [comment]
@AbhishekPAnil  Here is how it should look (region is a blue tag) - screenshot below
Link to FIGMA: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=4732-61038&mode=design&t=fTvgYPN2iPPCY7Rc-4



![Image](https://github.com/culturecreates/tech-support-tickets/assets/64489312/d587c622-9b76-4d47-8104-8034b374bac1)

**Comment by SyamBabu-M** [comment]
@dev-aravind Please add the region to search places API response.

**Comment by dev-aravind** [comment]
@SyamBabu-M The changes are up in staging.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED
