### ISSUE TITLE
Region in read only view (Places) doesn't match the taxonomy term for Regions

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#30]
The name in the taxonomy doesn't match what appears on the read only page. In the example below, Laval-des-Rapides (in the taxonomy) vs Laval-Des-Rapides (in Read-only view) - capitalization is different.
See this place: https://cms.footlight.io/dashboard/63457978637093005071a053/places/64d107f67d6aa80064322250

**Comment by MaudeFJ** [comment]
<img width="1020" alt="Capture d’écran, le 2023-08-07 à 14 47 15" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/29bf763a-a5f3-4cef-9d28-f5f01ed5df03">
<img width="1234" alt="Capture d’écran, le 2023-08-07 à 14 47 07" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/15103ca8-dfab-429b-8504-dc7c883b8bb5">

**Comment by saumier** [comment]
@AbhishekPAnil Please do not change the capitalization of the labels. 

Current behaviour: Laval-Des-Rapides
Expected behaviour is to have the same capitalization as in the taxonomy: Laval-des-Rapides

**Comment by AbhishekPAnil** [comment]
Fixed and updated in staging 
Added closes tag  to commit  [deee19c](https://github.com/culturecreates/footlight-app/pull/694/commits/deee19cef97e3719ecf3339bc27c3b8dbb6cc4e9)

**Comment by troughc** [comment]
Tested by checking signe laval calendar region Laval-des-Rapides and changing the case back and forth: PASSED
