### ISSUE TITLE
Enhancement: Search by Organization in Events listing page in the CMS

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#31]
User Stories:
As a user of the CMS, I want to find all events that involve a specific organization (no matter what is their role in the event). 
I want to find all events that a specific person is involved in (no matter their role)

Other fileters

I want to see all events within a geographic region or multiple regions

I want to see all events with a specific audience / audiences

I want to see specific event types (and filter those that are sub-event types of multipe parents exampel dance workshop vs dance performance)

....

Would this be a case where we could use a qualifier like 'person' or 'organization'. And are multiple entries supported separated by commas? Or should the user just have to enter the name of the organization?

**Comment by troughc** [comment]
@saumier Maude would like to be able to search for organizations on the event listing page. What do you think would be the best way to do this? (see comment above)

**Comment by MaudeFJ** [comment]
Pour le CSM c'est plus facile de juste chercher le nom de l'organisateur dans la barre de recherche pour trouver tous ces événements, peu importe qui de l'organisation a ajouté les événements. 
Et sur le front end je veux pouvoir regrouper rapidement tous les événements d'un même organisme sur une seule page même s'ils sont dans des lieux différents ou autres. (ex pour partager dans mes réseaux sociaux toutes les activités de tel organisme, OU lorsque l'organisme cherche à voir ses événements dans le calendrier ils vont chercher directement leur nom d'organisme et leurs événements ne sortent pas et ensuite ils m'appellent parce qu'ils pensent qu'il y a un problème dans la publication... )

**Comment by saumier** [comment]
@troughc The [Open API](https://api.footlight.io/api/#/Calendar%20APIs/CalendarController_getEventsByCalendarId) supports finding all events for a specific organization or person in the roles of organizer, performer or sponsor. 

```
person-organization (List of UUIDs of person and organization, optional) 
Select events by person or organization linked either as a performer or organizer or sponsor.
```

**Comment by troughc** [comment]
@MaudeFJ let's talk about this issue at our next meeting please.

**Comment by troughc** [comment]
Added https://github.com/culturecreates/footlight-calendar-api/issues/753

**Comment by troughc** [comment]
This feature has been added.
