### ISSUE TITLE
Tout Culture - time displayed on website not matching custom times on event

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#35]
BUG IN production: 
For Exposition « Michaëlle Sergile | Rasanblaj »:  the time on the website for Saturdays/Sundays shows as 12-4; however 12-5 is entered in the CMS for Saturdays and Sundays. Screenshot of website dates and times:
<img width="374" alt="Screenshot 2023-08-17 at 10 52 23 AM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/4af6c935-6e54-4047-abc6-82692eadb607">
The event in the CMS is: https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/645bb7957db98f0065dce2b5

This is also happening for other events that don't have an end time. For example https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/645bb7977db98f0065dce335

Start time is 6:30PM but it shows in the dropdown 18h (6PM) - 16h (4PM)
<img width="1035" alt="Screenshot 2023-08-17 at 10 58 36 AM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/1bcba28d-daa7-4db9-aef8-3d0f8911af39">

**Comment by troughc** [comment]
@AbhishekPAnil I am not sure if this one is for you or is happening in the backend? 
The issue is that some of the times that are displayed on the website don't match the times that appear in the CMS when we do recurring events (multiple dates) - if I am correct, both of these events used weekly recurring (and then, for the first one, I switched it to custom to add different times for different days).
Let me know tomorrow if you would like me to demo this issue to you.

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil I am not sure if this one is for you or is happening in the backend? 
> The issue is that some of the times that are displayed on the website don't match the times that appear in the CMS when we do recurring events (multiple dates) - if I am correct, both of these events used weekly recurring (and then, for the first one, I switched it to custom to add different times for different days).
> Let me know tomorrow if you would like me to demo this issue to you.

Ok I will check and let you know tomorrow

**Comment by troughc** [comment]
This issue is happening after the data is entered into the CMS.

**Comment by troughc** [comment]
@sahalali what is the status with this issue?

**Comment by dev-aravind** [comment]
@troughc the backend part is fine, I checked the API for fetching the event that you mentioned in the tout-culture website. 

For a Friday, say 18th of August, the timestamp of the subevent is 2023-08-18T16:00:00-04:00, which converts to August 18, 2023, at 4:00 PM

For a Saturday and Sunday, let's say 19th and 20th August, the timestamps are 2023-08-19T17:00:00-04:00 and 2023-08-20T17:00:00-04:00, which convert to August 19, 2023, at 5:00 PM and August 20, 2023, at 5:00 PM respectively.


footlight-open-api response :https://api.footlight.io/events/645bb7957db98f0065dce2b5

**Comment by troughc** [comment]
We will followup with MINIMAL in a live meeting. cc @sahalali @saumier

**Comment by saumier** [comment]
@troughc We explained the issued via email, and Minimal found the info clear and didn't think it necessary to have a meeting.
