### ISSUE TITLE
How to map réservatech disciplines 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#36]
Hello here is the full list  : 

Autre --> discipline / indéterminé
Cinéma --> discipline/ cinéma 
Conférence --> type d'événement / conférence 
Documentaire --> discipline / cinéma / documentaire 
Famille --> Type de public / jeune public 
Festival --> Type d'événement / festival 
Art de la parole --> Discipline / indeterminé 
Ballet / danse --> Discipline / danse
Blues / Jazz --> Discipline / musique / jazz + blues (is that possible??) sinon juste musique 
Chanson anglaise --> Discipline / musique 
Chanson autochtone --> Discipline / musique 
Chanson Française --> Discipline / musique 
Chorale --> Discipline / musique 
Conte --> Discipline / littérature / contes
Enfant / jeunesse --> type de public / jeune public
Humour --> Discipline / humour 
Magie --> Discipline / variété / magie 
Musique classique --> Discipline / musique / classique 
Musique du monde --> Discipline / musique
Noël --> Discipline / indéterminé 
Orchestre symphonique --> Discipline / musique / classique 
Rock / pop --> Discipline / musique / pop et rock (possible ?) sinon juste musique 
Théâtre --> Discipline / théâtre 
Variété --> Discipline / variété

Merci merci !

**Comment by troughc** [comment]
@saumier assigning this Mapping request to you (for co-motion) - in case you are already working on it.

**Comment by saumier** [comment]
@troughc I'm not working on it. I'm assigning to Suhail. Thx.

@sahalali Please map the keywords in the list above to their concept ids in Signé Laval's CMS. Thx.

**Comment by saumier** [comment]
@sahalali Please confirm my changes are correct. See comment on commit https://github.com/culturecreates/footlight-aggregator/commit/e37ff803f5ff3b0988ed91d3d443029993a6b029

**Comment by suhail-aliyar** [comment]
I interpreted "Blues / Jazz --> Discipline / musique / jazz + blues (is that possible??) sinon juste musique" means mapping Blues to Jazz and Blues also, Jazz to Jazz and Blues 
Blues => [blues concept_id, jazz_concept id]
Jazz => [blues concept_id, jazz_concept id]

However, as you added  Blues=> [blues concept_id] and Jazz => [jazz_concept id] makes sense.

**Comment by suhail-aliyar** [comment]
@saumier Added unit tests

**Comment by saumier** [comment]
@sahalali I added an additional test that will require some changes to the mapping.json for this case: "Blues / Jazz" => [blues concept_id, jazz_concept_id].   Currently this new test is failing. Please look into making the test pass, or  helping me understand if the test is not what is expected. I also noticed that the test loaded the mapping json from co-motion. The test needs its own mapping json to make it immutable. I propose you add a local mapping to the test. Thx.

**Comment by suhail-aliyar** [comment]
@saumier Currently, we consider the whole text for mapping. If we need to support "Blues / Jazz", we either need to check if the string contains a condition or split "Blues / Jazz" to [ "Blues", "Jazz"], if the delimiter is '/'.
If you think we need to support  **"Blues / Jazz" => [blues concept_id, jazz_concept_id]**, then we will need some code changes.

**Comment by saumier** [comment]
@sahalali Does the mapping support regex?  Try this '/blues/i' to match "Blues / Jazz" => [blues_concept_id] and '/jazz/i' to match "Blues / Jazz" => [jazz_concept_id]

**Comment by saumier** [comment]
@sahalali The test I created was not passing so I didn't want to leave it in the main branch for too long before fixing. So I moved the mapping into the code and made the tests pass. I also added a mapping with an invalid regex just incase. The code was already working but instead of adding "/blues/i" which is the entire regex I added only ".*blues.*" since the code was already wrapping the string into a regex. I also switched to user friendly conceptIDs to make it easier to read the tests. Please take a look at my 4 commits into main.

**Comment by saumier** [comment]
@troughc Today I ran another aggregator import for Co-motion. All the disciplines of events that have not been edited by another user should now be updated.

You can check this event which can only be mapped because of a keyword Jeunesse from Reservatech:
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/650297b2a59a070066be6cb8

https://console.footlight.io/events/footlight%3Aco-motion-ca_passe-partout-coucou-passe-partout-le-spectacle

**Comment by suhail-aliyar** [comment]
> @sahalali The test I created was not passing so I didn't want to leave it in the main branch for too long before fixing. So I moved the mapping into the code and made the tests pass. I also added a mapping with an invalid regex just incase. The code was already working but instead of adding "/blues/i" which is the entire regex I added only "._blues._" since the code was already wrapping the string into a regex. I also switched to user friendly conceptIDs to make it easier to read the tests. Please take a look at my 4 commits into main.

It looks good to me @saumier
