### ISSUE TITLE
Design change: update french label "unpublish event" in right-click menu (and elsewhere)

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#37]
Dépublier 
et
Dupliquer 
Ça se ressemble vraiment beaucoup et dépublier, c'est pas un mot du dictionnaire en français... 
Est-ce qu'on pourrait penser à d'autre option genre :
Passer en brouillon 
Retirer
<img width="175" alt="Capture d’écran, le 2023-09-13 à 14 10 50" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/8fe158aa-dd71-4f84-9179-818aac79c237">

**Comment by troughc** [comment]
@AbhishekPAnil this is the issue I spoke with you about this morning/evening.

**Comment by troughc** [comment]
@AbhishekPAnil I made the change in translationFr.json. Please search for keyword unpublishEvent  (around line 400).

(I commited it to the develop branch)

TAke a look and let me know - if it passes your test, please assign it back to me.

**Comment by AbhishekPAnil** [comment]
Tested in staging:
French translation for Unpublish event is updated to Passer en brouillon

TEST PASSED

**Comment by troughc** [comment]
Tested in Staging: PASSED
