### ISSUE TITLE
Not approving reviewers events: Event approving workflow

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#39]
### Workflow friction with pending review events
When an ADMIN (Maude) reviews an event and wants to give it back to the GUEST who created the event (by setting it to draft), they have to first publish and then unpublish the event (before the user can resume their work).The ADMIN cannot use the right-click menu in the Event list nor click the Save as Draft button in the event details to reset the event to DRAFT (the event remains in a Pending Review State).
Note: Usually ADMINS work with the draft and pending review filter on for events, so they lose sight of the event when they publish it (and have to clear their filters to find the event in order to set it back to draft).

### User story
As an ADMIN/EDITOR, I want to be able to set events sent to me for review back to draft without publishing them, so that the GUEST contributor can make necessary changes to the event.
**Acceptance criteria:** An ADMIN and/or EDITOR able to convert a PENDING REVIEW event to a DRAFT event from the Event Details page and from the right-click menu in the Event list.

Link to Design: https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7724-38128&mode=dev

**Comment by troughc** [comment]
@MaudeFJ how often does this happen to you on a weekly or monthly basis? How often do you lose site of your events when you publish them.

**Comment by MaudeFJ** [comment]
It depends, but i would say it could be up to every time i'm reviewing event (so like twice a week) or like once a month (if i'm doing most of the changes myself and publish directement without having them make the changes)

**Comment by troughc** [comment]
Design is working on this feature. Work is continuing week of November 16

**Comment by troughc** [comment]
Link to design:
https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7724-38128&mode=dev


@sahalali please take a look and estimate work. the change in the UI is a new 'revert to draft' button that enables the Admin/Editor to change the status of the pending review event to a draft event (so the guest can continue editing).

cc @AbhishekPAnil  you may need to do some front end work as well.

**Comment by suhail-aliyar** [comment]
Estimation: 8 H 
1. Update the Event publish API. Add an extra param to set the new publish state. Also verify the new publish state before assigning
2. Peer review
3. Unit testing

**Comment by dev-aravind** [comment]
@AbhishekPAnil The backend changes are up in staging, please update the frontend.

**Comment by AbhishekPAnil** [comment]
@troughc Do we need to add the "Revert to draft" option to the event list right click dropdown .
https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=3735-80576&mode=design&t=00FOzTl9oDNbkR7V-4

Also could you provide the french translation for "Revert to draft" .Thanks

**Comment by AbhishekPAnil** [comment]
@troughc To implement the below design we need additional changes in the backend .


![Image](https://github.com/culturecreates/tech-support-tickets/assets/117100211/ce9f8365-bcd1-4cd2-b0e6-6751ff8c6937)



cc @sahalali

**Comment by troughc** [comment]
> Do we need to add the "Revert to draft" option to the event list right click dropdown .

@AbhishekPAnil yes please do. Also the translations for this are in the [FIGMA](https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7724%3A38128&mode=design&t=XtL42kw09c7uzqXK-1)

Also, when you add that message, could you also fix a typo in another message the same time? There is a grammatical error IN FRENCH ONLY. 
This message: Cet événement est en train d'être valider.  _(this event is under review)_
Change to this: Cet événement est en train d'être validé.


Assigning to @sahalali for the backend work that is required.

**Comment by dev-aravind** [comment]
@AbhishekPAnil I added a new boolean field called reviewFailed. If reviewFailed is true, it means that the event was moved from review state to draft state by an admin. Let me know if you have any questions.

**Comment by troughc** [comment]
Tested - PASSED
I like the fact than I can make a change (or not) as an admin and then still revert to draft for the original (guest) user to continue their work. 
Looks great!
