### ISSUE TITLE
Bug order of the user name 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#41]
Mes événements is not first anymore 
<img width="208" alt="Capture d’écran, le 2023-10-05 à 14 12 45" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/7694a363-82c2-4fa2-ad4a-76b049731c88">

**Comment by troughc** [comment]
@AbhishekPAnil this issue is happening in both the production and staging servers. Can you please check it? 
Expected behavior: My Events should be listed first in the dropdown.
Thanks.

**Comment by AbhishekPAnil** [comment]
Fixed and updated in staging.
Added closes tag to commit [a181223](https://github.com/culturecreates/footlight-app/pull/673/commits/a18122330500ceb1a4203da0f075281974ec1db5)

**Comment by troughc** [comment]
Tested in Staging: PASSED
