### ISSUE TITLE
Long loading time when looking for place and organization 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#42]
Since we are looking in all of arts data when sherching for a place, person or organization, the wait time before the result come up is longer.  would that be something we can improve ? (and it also seems like the result from footlight are the one taking longer...)

**Comment by troughc** [comment]
@MaudeFJ this should be working. Can you please retest and let us know if you still have an issue.

**Comment by MaudeFJ** [comment]
https://github.com/culturecreates/tech-support-tickets/assets/135066077/f98285d8-3285-4942-8f2b-6ed728f365ae

It's still long ...

**Comment by troughc** [comment]
Thanks @MaudeFJ.
I can confirm that it is also long for me. I am reopening this issue.

**Comment by troughc** [comment]
@AbhishekPAnil the response time is slow when a user is searching Location, Organizer or another search field. I can confirm it is slow for me as well, in all workspaces. For an example, please see the video above of a search for a location. 
Can you please investigate? 
Also, the 'spinner' is not appearing.
Thanks!

**Comment by AbhishekPAnil** [comment]
Sure ,I will look into this.

**Comment by AbhishekPAnil** [comment]
@dev-aravind After debugging this issue with /entities api,I found that after giving organization and person classes ,the api becomes slow.

**Comment by dev-aravind** [comment]
@troughc This is caused by the Artsdata API response time. Let's discuss during the standup about this.

**Comment by dev-aravind** [comment]
From the standup on 24-11-2023, we decided on 2 improvements.

For @dev-aravind :Update the backend search API to make searching for Artsdata(or any external source) separate from the CMS.

For @saumier : Update Artsdata API to try and search for organizations and people with a single API call.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The new API to get entities from external sources is up in this [branch](https://github.com/culturecreates/footlight-calendar-api/tree/enhancement/issue-42). Please update the front-end side.

**Comment by AbhishekPAnil** [comment]
The backend and UI changes are updated in staging

**Comment by troughc** [comment]
Tested staging in chrome as a guest and as an admin
@AbhishekPAnil @dev-aravind something is amiss with the search - nothing is appearing in my search dropdowns. This happens wherever the search field appears (in event details and in the other workspaces, like people, places and organizations) 
Here are some screenshots, one with the developer tools open.
GUEST TEST
Before typing in Location field:

<img width="491" alt="Screenshot 2023-11-29 at 4 42 16 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/e8ad9c62-b7d8-4e65-8c9c-97200e4c656a">

After typing in Location field:
<img width="860" alt="Screenshot 2023-11-29 at 4 42 47 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/3f6a126c-f1cb-4675-b39e-5b78f1a23bd2">

ADMIN TEST
Before typing

<img width="616" alt="Screenshot 2023-11-29 at 4 43 54 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/bdfd3d87-7117-466b-a827-404d69e6d1b1">


After typing **with the developer tools open**

<img width="1178" alt="Screenshot 2023-11-29 at 4 46 47 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/5b41137f-c803-444a-8a8a-ec953e72013c">

**Comment by dev-aravind** [comment]
@troughc Apologies, this was caused due to an unexpected revert of the develop branch. I have re-enabled the feature now. Please have a look at it and let me know if you face any issues.

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED -  thank you!
