### ISSUE TITLE
Design - Organizer prompt position

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#43]
I've already have talked about it in the past but I want to insist on it again. 
In the retroaction i'm giving to the collaborateurs i've seen some pattern and the most common mistake they make, is forgetting to put themself as organizer... 
And i think its telling that there might be a an issue with the placement of the box they need to fill.
thanks

**Comment by troughc** [comment]
We are looking at this one @MaudeFJ .

**Comment by troughc** [comment]
@AbhishekPAnil can you please move the Organizer field above the Image field in the CMS?

<img width="499" alt="Screenshot 2023-11-13 at 11 51 06 AM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/7e184aca-86c9-4a2c-bd5e-0c616f5b5c4b">

**Comment by troughc** [comment]
Tested staging in Chrome: PASSED

**Comment by troughc** [comment]
@MaudeFJ The organizer field has been moved to above the Image. This issue is now closed. Have a greate day!
