### ISSUE TITLE
Nice to have : filtre date d'ajout pour les users

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#44]
Right now we can only filter them by name and It would be pratical to filter them by date to keep the count of how many user we have and who we added last 
<img width="382" alt="Capture d’écran, le 2023-12-01 à 09 51 31" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/1c8d5fbb-1ec4-4369-8d7f-246a11eb820b">

**Comment by troughc** [comment]
I am combining this request with tech support ticket #53

**Comment by troughc** [comment]
@MaudeFJ this feature has been implemented. YOu can sort users by date invited.
