### ISSUE TITLE
Text in french need corrections 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#46]
<img width="491" alt="Capture d’écran, le 2024-01-23 à 14 10 04" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/8e5a2b58-5c69-4de2-bfa8-95f978b67a5e">

le bon événement, un nouvel
Merci !

**Comment by troughc** [comment]
@AbhishekPAnil, the linked data text is wrong for events in French (wrong gender). The correct copy in french is available in the copy cms document - I tagged you so you know where to find it. Please update it in the UI and thank you!

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil, the French linked data text is wrong on the EVENTS and PLACES forms (wrong gender). The correct copy in french is available in the copy cms document - I tagged you so you know where to find it. Please update it in the UI and thank you!

Noted

**Comment by AbhishekPAnil** [comment]
@troughc Do we have to changes this in other workspaces ?

**Comment by troughc** [comment]
Tested: french text looks good in all workspaces - PASSED
