### ISSUE TITLE
Adding a photo to a place

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#49]
Right now, on our main map, we display places and there is a mockup photo for each place. There is nos fild to add an image to a place.

![Capture d’écran 2024-02-06 151806](https://github.com/culturecreates/tech-support-tickets/assets/135066781/da8c494b-ee23-4f9c-9074-3047254b7108)

**Comment by troughc** [comment]
@IPlouffe yes this is possible. I will put add it to the roadmap and let you know when we can do it.

**Comment by troughc** [comment]
@AbhishekPAnil this feature requires adding the image component to Places.

**Comment by AbhishekPAnil** [comment]
@troughc We already have a field to add images in the places form, right?


![Image](https://github.com/culturecreates/tech-support-tickets/assets/117100211/3d53de16-f8b2-4d71-8703-710142a8ab64)

Currently we are not displaying the place images in the listing page or in any of the form where we use a place including the place read only page.Are you referring to displaying the image in these areas?

**Comment by troughc** [comment]
@IPlouffe Oops, I misspoke earlier - the option to add an image to a place already exists in the Places workspace (see screenshot in previous comment).

Does Minimal need guidance on connecting the image to the public facing website? Let me know.
