### ISSUE TITLE
Bug dans la navigation 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#5]
Si je sélectionne les événements brouillons, puis je désélectionne, puis je clique sur un événement et je reviens vers tous les événements ma sélection de brouillon est encore là même si je l'ai décoché plus tôt .
**TRANSLATION for dev team:** 
This happens when I select draft events, then deselect the filter, and then click on an event and go back to all events:  my draft selection is still there. 

**Note from Caitlin to @MaudeFJ** : This is a known issue and documented in an issue called: Enhancement: Reviewing events in new cms - navigating/reviewing with filters persisting #235
For now, the way to remove a filter (in this case, draft event) is to click the Clear button (rather than deselecting draft from the filter).  I have requested this to be improved as an enhancement.
cc @saumier 

https://github.com/culturecreates/tech-support-tickets/assets/135066077/a0faabf4-d6bc-4104-8001-af3fdc26cb3a

**Comment by troughc** [comment]
This is now fixed @MaudeFJ . thanks.
