### ISSUE TITLE
Navigation pages user

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#51]
The "retour à la liste des utilisateurs" bouton always send me back to the fist page regarderless of wich page i was on. 

https://github.com/culturecreates/tech-support-tickets/assets/135066077/7473a1ad-a36e-4473-b276-aee797d879ca

**Comment by SyamBabu-M** [comment]
@troughc Please test this [here](https://pr-1055.dla06mbe0wyl7.amplifyapp.com/). I couldn't link the pr to this issue.

**Comment by troughc** [comment]
Tested on Chrome and Safari: PASSED

**Comment by AbhishekPAnil** [comment]
Deployed in production 
https://github.com/culturecreates/footlight-app/pull/1063

**Comment by troughc** [comment]
Hi @MaudeFJ,

This navigation issue related to settings (users) is now fixed. The issue is closed.
Thank you for drawing our attention to this.
Caitlin
