### ISSUE TITLE
Recover deleted l'oeuvrelue event for Maude - Signé Laval

### ISSUE THREAD

**Issue by saumier** [culturecreates/tech-support-tickets#52]
The event with a name that contains `l'oeuvrelue` was deleted by accident by Maude. She would like to restore it.

This not the same as https://cms.footlight.io/dashboard/63457978637093005071a053/events?page=1&order=asc&sortBy=upcomingEventDate&query=oeuvrelue

**Comment by suhail-aliyar** [comment]
@troughc There were two events marked obsolete matching the condition **query=oeuvrelue**. Restored both events as I wasn't sure which one to restore. 

Details of events restored:
1. https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/65b7c9368468f40064839332
2. https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/65b7d6a48468f4006483b04f

**Comment by troughc** [comment]
Looks good, thanks @sahalali. Please close this issue.
