### ISSUE TITLE
Being able to sort places, organizations, people and users by Creation date (EDITED TITLE)

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#53]
Feature enhancement: Make default SORT options for people places and organizations consistent with TAXONOMIES sorting options. Also for User Management listing
Potential update to people, places, organizations and User Management:
- Add Creation date to the sort field (where necessary, change it to a dropdown like it is in Taxonomies and Events).

<img width="890" alt="Capture d’écran, le 2024-03-01 à 10 08 47" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/945b03cd-fe5a-4283-9aa9-009f046e5972">

**Comment by troughc** [comment]
idea is to make defautl sorting options for people places and organizations consistent with Events sorting options.

**Comment by troughc** [comment]
@sahalali does this need backend work or just app work? thanks.

**Comment by suhail-aliyar** [comment]
Yes, this will require some backend changes.

**Comment by troughc** [comment]
okay, I leave it to you to assign to the appropriate team member. I am adding the tag, estimate needed.

**Comment by suhail-aliyar** [comment]
Backend estimation: 8 Hours.

Update the following API to support sort by createdAt property
1. GET /places
2. GET /organizations
3. GET /people
4. GET /user (sort by invitedOn)
@troughc Currently, we only persist the date of invitation sent for user listing. Do we need to list users by date of joining(accepting invitation)? Please advise.

**Comment by troughc** [comment]
> 4\. [@troughc](https://github.com/troughc) Currently, we only persist the date of invitation sent for user listing. Do we need to list users by date of joining(accepting invitation)? Please advise.

@sahalali thanks for the idea - we may consider this as a future enhancement, but not necessary right now
Thanks

**Comment by suhail-aliyar** [comment]
Backend estimation: 8 H

**Comment by AbhishekPAnil** [comment]
Frontend estimate: **2.5H**
Add sort by dropdown integration to Organization,People and Places.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The backend changes are up in staging. You can pass the param metadata.createdAt to sort entities using created date and for users you can pass the param invitedOn to sort them by invited date.

**Comment by AbhishekPAnil** [comment]
@troughc 
Use the below link to test this feature.
https://pr-1087.dla06mbe0wyl7.amplifyapp.com/

Please checkout the label for created date at the users listing page.The users are actually sorted using the invited date.Let me know if you want to change the label and I think it would be good to show the respective date below the invited by text.Let me know what you think about this.Thanks!

**Comment by troughc** [comment]
Tested in Chrome and Safari: everything is working well, thanks!
@AbhishekPAnil I would like to request a small change to the text AND I like your ideas about created date for users.  

Can you please make these changes?

In **English only**, please make this change everywhere (except users):
Change Created date to **Date created**

Change the label for users Only in Engish and French:
ENGLISH: Change Created date to **Date invited**
FRENCH: Change to **Date d'invitation**


IF this is also easy to do you can add a line text below the status that indicates the invited date. If not, we should put this in a separate issue as an enhancement (push to another time).

**English example**: Invited 19-DEC-2022
**French example**: Invité le 19-DÉC.-2022
OR
**English example**: Invited 19-DEC-2022 by ctroughton
**French example**: Invité le 19-DÉC.-2022 par ctroughton

**Comment by AbhishekPAnil** [comment]
@troughc The changes are updated in the PR link.Please check it out and let me know if there are any more changes required.Thanks!

**Comment by troughc** [comment]
to solve the issue with the missing text below the status that indicates the invited date, please add this to all of them EXCEPT for Culture Creates Support (the superadmin). Please add this to users in both calendars as necessary. Thanks @AbhishekPAnil !
the text: 
English example: Invited 12-DEC-2022 by csupport
French example: Invité le 12-DÉC.-2022 par csupport

**Comment by dev-aravind** [comment]
@troughc The users with no invited dates:

Isabelle Plouffe, joined date: 2022-08-30
Karine Fleury, joined date: 2022-08-31
Eric Legros, joined date: 2022-09-13
Stephanie Giroux, joined date: 2022-09-20
Caitlin Troughton, joined date: 2022-08-28
Gregory Saumier-Finch, joined date: 2022-08-27

What do you want their invitedOn dates to be?

**Comment by troughc** [comment]
Please use the above as the invited date

**Comment by dev-aravind** [comment]
@troughc These users now have an invited date, and their invitor is set as Culture Creates Support.

**Comment by troughc** [comment]
@dev-aravind @AbhishekPAnil I tried using this link to test this but i don't see the dates:

https://pr-1087.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/settings?page=1&order=asc&sortBy=invitedOn

**Comment by dev-aravind** [comment]
@troughc This is because the dates were added to the production database rather than the staging one as it made more sense to me. For now, I have synced the staging and production databases to fetch the changes to staging. You can review it now.

**Comment by troughc** [comment]
Tested: PASSED
