### ISSUE TITLE
add people and Organizations to CMS from the artist directory provided by Signe Laval in a CMS file

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#54]
Could we do a dump of the répertoire des artiste https://signelaval.com/fr/repertoire-culturel into footlight ? 

Most recent  file provided by Signe Laval September 26, 2024
CSV file that contains people and organizations in two different tabs. This data is coming from a different Signe Laval database. Here is the link:
[contacts répertoire sept 2024 (1).xlsx](https://github.com/user-attachments/files/17119800/contacts.repertoire.sept.2024.1.xlsx)

**Comment by troughc** [comment]
@MaudeFJ can you send us a data dump of your repertoire of artists in a spreadsheet? 
Or are you asking us to scrape your website to get them?
thanks!

**Comment by MaudeFJ** [comment]
Hello,
I have a cvs I can send via email



Maude Fraser

Responsable de Signé Laval  ​


450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3
  [cid:63a5cbfd-53b9-4779-9ea7-482524ce64e6]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Twitter<https://twitter.com/Signe_Laval>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.





________________________________
De : troughc ***@***.***>
Envoyé : 3 avril 2024 09:55
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Assign ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Question (Issue #54)


Assigned #54<https://github.com/culturecreates/tech-support-tickets/issues/54> to @MaudeFJ<https://github.com/MaudeFJ>.

**Comment by troughc** [comment]
@MaudeFJ did you still want this? I don't think we received your CSV file?

**Comment by MaudeFJ** [comment]
[contacts-2024-05-17 (2).csv](https://github.com/user-attachments/files/15888086/contacts-2024-05-17.2.csv)
Hello ! oups ! Should i had une colonne with Laval so that they have the right taxonomies when they get in. Could we do this like twice a year for our new artiste in the répertoire ? Merci

**Comment by troughc** [comment]
@saumier please see Maude's request above - to add her artist directory to the CMS. She is also asking if she should add a column for Laval? I am not sure, can you please answer this question too Gregory, before assigning it to our team member? Thanks.

**Comment by saumier** [comment]
@troughc Yes. Maude should add a column for Lavalois artists. I'm assigning back to you.

**Comment by troughc** [comment]
HI @MaudeFJ Yes, please add a colu,n for Lavalois artists and attach the updated CSV file.

**Comment by troughc** [comment]
@MaudeFJ just checking back to remind you. Could you add a column to your spreadsheet for Lavalois and then send us the updated CSV file?

**Comment by MaudeFJ** [comment]
[contacts-2024-05-17 (1)(contacts-2024-05-17 (1)).csv](https://github.com/user-attachments/files/15977930/contacts-2024-05-17.1.contacts-2024-05-17.1.csv)
Il y en a plusieurs qui sont déjà dans le cms

**Comment by troughc** [comment]
caitlin to try in staging: done
passing to tech team.

**Comment by suhail-aliyar** [comment]
People have been added to the Signe Laval calendar. There were 43 individuals already in the CMS, so they have been excluded from the upload. Additionally, images of the existing people have been included. 
Here is the list of people excluded for reference:


[signe-laval people - Sheet6.pdf](https://github.com/user-attachments/files/16108099/signe-laval.people.-.Sheet6.pdf)

**Comment by troughc** [comment]
@sahalali, my apologies. We just realized that this list contains both people and organizations. Can you please remove.

**Comment by troughc** [comment]
@MaudeFJ FYI, we uploaded the spreadsheet to people, and then realized that the spreadsheet contains both people and organizations.

To upload these lavalois, we would need them to be separated by their type (class) - those that are people and those that are organizations.

**Comment by suhail-aliyar** [comment]
@troughc Here is the Google Sheet I worked on. This sheet will be helpful when uploading to CMS. You need to delete the rows that do not pertain to people.
https://docs.google.com/spreadsheets/d/1O6nTltC-YbIwsRlqTiB2ZH5a8rCcY3rRaBNSafKAFxA/edit?usp=sharing

**Comment by troughc** [comment]
@MaudeFJ can you please use the spreadsheet in the previous comment to update for the next upload? Notice column H, called 'type'. This is where you see the type (class), i.e. Person or Organization.
There are two steps:

1. Duplicate the spreadsheet so you have two. This will allow you to separate the two different types you will have in column H.

2. In column H, you can change Person to Organization, where appropriate. Only keep Organizaitons in one spreadsheet and Persons in the other.

Let me know if you have questions.

**Comment by troughc** [comment]
Hi @MaudeFJ Because this is from July, the spreadsheet we shared may no longer be up to date - i.e. changes may have been made in the CMS since then. 
Do you still want to do this? If yes, we will need to regenerate the spreadsheet and start afresh. It is best that we do it ASAP after providing a spreadsheet so that no work gets overwritten.

cc @saumier @sahalali

**Comment by MaudeFJ** [comment]
True, ill get back to you with a new one

**Comment by MaudeFJ** [comment]
Hello, 
I have not seen the other doc... But would this be alright ? 
There is 2 tab : personnes and organisations 
[contacts répertoire sept 2024 - Organismes.csv](https://github.com/user-attachments/files/17119798/contacts.repertoire.sept.2024.-.Organismes.csv)
[contacts répertoire sept 2024 (1).xlsx](https://github.com/user-attachments/files/17119800/contacts.repertoire.sept.2024.1.xlsx)
The ones that already have id are already in footlight... 
Alors, I would wish to be able to complete this document with the new id ? 
Would you be able to export the one from footlight so I can complete this one easily ? 
merci !

**Comment by troughc** [comment]
@sahalali 
Maude of Signe Laval has shared a new spreadsheet that contains people and organizations in two different tabs. This data is coming from a different Signe Laval database. Here is the link:
[contacts répertoire sept 2024 (1).xlsx](https://github.com/user-attachments/files/17119800/contacts.repertoire.sept.2024.1.xlsx)

The CSV file contains new people and new organizations that need to be added to the Signe Laval CMS. It also contains people/orgs that are already in the CMS (the footlight ID is noted the spreadsheet). 

Can someone on the team please do the following before October 2:
- Reconcile and upload the new people and organizations to the signe laval CMS
- Export a report of all the new people and orgs with their footlight IDs (in two tabs).

Thank you

**Comment by troughc** [comment]
@dev-aravind I am tagging you on this ticket as we talked about it this morning. Please see the previous comment.

**Comment by dev-aravind** [comment]
@troughc The data is now imported to CMS.

[Report](https://docs.google.com/spreadsheets/d/1tb3pcjEEnpGy2aGY2ZbP_K7lkuYO1Hu09pPiFh4t0zo/edit?gid=1243993828#gid=1243993828) of new entities

[Source data](https://docs.google.com/spreadsheets/d/15LFDcSegJebcQbIWPSHlTuDLddmhmlN4vuHExnwChIY/edit?gid=468845017#gid=468845017) used for bulk upload.

[Organizations](https://cms.footlight.io/dashboard/63457978637093005071a053/organizations?page=1&order=desc&sortBy=metadata.createdAt) list in CMS.

[People](https://cms.footlight.io/dashboard/63457978637093005071a053/people?page=1&order=desc&sortBy=metadata.createdAt) list in CMS.

**Comment by dev-aravind** [comment]
@troughc The report is now updated with the ids of the entities.

**Comment by MaudeFJ** [comment]
Amazing ! 
i don't have access to the docs for now, let me know when I can take over 
Thanks

**Comment by troughc** [comment]
@MaudeFJ this is the report you need and you have access: 
[Report](https://docs.google.com/spreadsheets/d/1tb3pcjEEnpGy2aGY2ZbP_K7lkuYO1Hu09pPiFh4t0zo/edit?gid=1243993828#gid=1243993828) of new entities

These links are to a view in the CMS, sorted by most recently added: 
[Organizations](https://cms.footlight.io/dashboard/63457978637093005071a053/organizations?page=1&order=desc&sortBy=metadata.createdAt) list in CMS.

[People](https://cms.footlight.io/dashboard/63457978637093005071a053/people?page=1&order=desc&sortBy=metadata.createdAt) list in CMS.

The other source data was what the dev team used to upload your new artists from the repertoire of artists you shared - so I don't  think you need it. 

Let me know if you have any issue accessing the report or list views.

**Comment by troughc** [comment]
@MaudeFJ I am closing this issue, but you can still add a comment if you need anything more.

**Comment by MaudeFJ** [comment]
i'm all set
