### ISSUE TITLE
Widget : Filter by "type de public"

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#55]
I really think there would be a use for this.

**Comment by troughc** [comment]
@MaudeFJ this feature will be implemented with a Settings update. The idea is that you will be able to select your own filters based on taxonomies. Stay tuned!

**Comment by troughc** [comment]
@MaudeFJ this feature has been implemented. You do this by making the audience taxonomy available as a filter and then turning it on in settings.

**Comment by MaudeFJ** [comment]
Hello, 
I just tried it but it's not working on my side, could it be beacause of cache ? 

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/1e938900-facb-4c38-9bb2-04f0690175e5" />

<img width="361" alt="Image" src="https://github.com/user-attachments/assets/487e932c-e4c7-43e0-9c8a-6ad84c317e72" />

<img width="487" alt="Image" src="https://github.com/user-attachments/assets/d7feaab3-4d6e-4473-ad58-32e3f2ace9f8" />

**Comment by troughc** [comment]
@MaudeFJ the 'Publics' filter is available in the Events list view:

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/80874a8a-0581-4d94-b3ce-fd70e23cb738" />

So it must have been a cache issue.

**Comment by troughc** [comment]
FYI: If you are trying to use 'public' for the listing widget setup, it doesn't apply- only the filters that appear in your screenshot are available.

**Comment by MaudeFJ** [comment]
is it possible to add public in the widget filter ?

**Comment by troughc** [comment]
@MaudeFJ Can you give me some background - what is the user story? How do you want to use this filter?
Do you want to include events of one kind of audience type on a partner's site? Or do you want to be able to filter events on a partner's site by audience?

How many partners do you have who want to do this?

Thanks.

**Comment by MaudeFJ** [comment]
I want a widget with all the event for adolescent and i want to offer some maison des jeunes or organisme like https://trouvetaressource.com/fr/jeunes  to put it on their website. 
i don't know how many I did not ask since this option was not available yet. I can do a little survey.

**Comment by troughc** [comment]
A survey would be great.
