### ISSUE TITLE
User Settings: Add ability for users to edit specified People in the CMS

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#56]
Today, Admins can enable Contributor/Guest users to edit specified organizations that they did not create. This is done in the User settings.
Add same ability for users to have edit access to specified People (selected by the Admin)

### Action:
In User settings, under Calendar section, Add ability to link People in user profile. In the image below, you can see how it looks for Organizations:

![Image](https://github.com/culturecreates/tech-support-tickets/assets/64489312/807d5fc4-aeb3-4d55-9f95-2889f9a6fab7)

To add this ability to specify people, use the same approach and add a search field below the Organizations section in the image.

Text ENGLISH:

**Title:** People
**body text:** Give this user edit access to one or more people.
**Search field default text:** Search People

**NOTE: FIX** default text in organizations Search field. **Change to:**  Search Organizations

Text French:

**Title:** Personnes
**body text:** Donnez à cet utilisateur un accès de modification à une ou plusieurs personnes.
**Search field default text:** Recherchez des Personnes

NOTE: FIX errors for organization text. some of the text is in English in the french UI. Please update: 
**body text:** Donnez à cet utilisateur un accès de modification à une ou plusieurs organisations.
**default text in the organizations Search field. Change to**: Recherchez des Organisations.

**Comment by dev-aravind** [comment]
@AbhishekPAnil The backend part is completed and up in staging right now. Let me know if you need any other support.

**Comment by SyamBabu-M** [comment]
@troughc Please test this issue [here](https://pr-1072.dla06mbe0wyl7.amplifyapp.com/)

**Comment by troughc** [comment]
Tested on chrome and safari: PASSED

**Comment by AbhishekPAnil** [comment]
Status : Deployed to production
