### ISSUE TITLE
Urgent - Error when saving

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#58]
When trying to published or save this event https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/660e3872140606006462c11a I have this error
<img width="1014" alt="Capture d’écran, le 2024-04-12 à 14 12 04" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/23bd9180-446e-4f3b-a6cb-087d502f5438">

**Comment by troughc** [comment]
@AbhishekPAnil or @sahalali please take a look at this error. All required fields are filled but the user cannot save or publish the event.
cc @saumier

**Comment by suhail-aliyar** [comment]
I tried publishing this issue and publishing the issue worked for me and @AbhishekPAnil. However, the issue with saving the event persists. @AbhishekPAnil will look into it. 

I successfully published this issue and it worked for me and @AbhishekPAnil. .

**Comment by AbhishekPAnil** [comment]
cc @AbhishekPAnil 
Bug report :

TypeError: ee.trim is not a function
    at AddEvent.jsx:503:49

**Comment by AbhishekPAnil** [comment]
After debugging:
The issue was caused because of a change in the response format in offerconfiguration 


![Image](https://github.com/culturecreates/tech-support-tickets/assets/117100211/32805913-e94e-4259-8368-0afc0733462a)

**Comment by suhail-aliyar** [comment]
The issue with Saving is now fixed.

**Comment by troughc** [comment]
Thanks, looks good on my side. @MaudeFJ this issue is now fixed in Production. You can retest on your side with the same event:
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/660e3872140606006462c11a
