### ISSUE TITLE
nice to have : pop up with nouvelle consigne dans le calendrier 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#60]
When i added the taxonomie Laval for the org. and artist i send an email saying it was now obligatoire, 4 person read it... 
Now with the new dev,  i want them to add a performer all the time event if they are not lavallois, big change, it would be cool that there is like a costumable pop up feature where i could say "Now you need to add performer on all your event that have performer etc etc. "
Merci

**Comment by troughc** [comment]
Hi Maude, we already have popup messages that tell users they must fill in a field: when you make a specific field mandatory (using the new settings section 'Mandatory fields'), the user will be required to add something to that field. If they don't they will get a popup telling them they need to (add a performer).

However, if the field is not mandatory, they won't get a popup. I think you must just communicate your wishes to your contributors or make it mandatory.

**Comment by MaudeFJ** [comment]
Hello I just added the mandatory field!
But I don't remember how to add the filters...


Maude Fraser

Responsable de Signé Laval  ​


450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3
  [cid:58880984-e699-44c0-8861-1145d0a9cd45]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Twitter<https://twitter.com/Signe_Laval>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.





________________________________
De : troughc ***@***.***>
Envoyé : 4 juin 2024 14:30
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Assign ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] nice to have : pop up with nouvelle consigne dans le calendrier (Issue #60)


Assigned #60<https://github.com/culturecreates/tech-support-tickets/issues/60> to @MaudeFJ<https://github.com/MaudeFJ>.

**Comment by troughc** [comment]
@MaudeFJ in the taxonomy you want to use as a filter, turn on Rendre ce type de taxonomie disponible en tant que filtre. 
Then go into calendar settings and in the filter section, select the taxonomy from the dropdown.
