### ISSUE TITLE
2 events disapeard

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#61]
[event canopée.pdf](https://github.com/culturecreates/tech-support-tickets/files/15178576/event.canopee.pdf)
Sophie from Canopée added atelier 1 and it was not there when I went to validate them. (now she made them again) but maybe they were trash.

**Comment by troughc** [comment]
@saumier, please take a look into this.

**Comment by saumier** [comment]
@troughc I am assigning back to you. The text in the PDF is in French so if you want Suhail to look into it in needs to be translated to English.

**Comment by troughc** [comment]
@sahalali, the events that Maude was talking about were created April 30th according to the email thread. My undestanding is that the two events were called "canopée. Please investigate to see if these events were accidentally deleted. If you don't find anything, just let me know.

Wed 2024-05-01 0918
To:Maude Fraser <m.fraser@culturelaval.ca>
I may have deleted them by mistake, but I honestly don't know how I would have done it.
the only options I see are Save as Draft, Send for Validation and Duplicate Event.

I created **all the workshops yesterday, starting with the first ones.**
I've just recreated them and sent them for review.

Mer 2024-05-01 0918
À :Maude Fraser <m.fraser@culturelaval.ca>
Ça se peut que je les ai supprimés par erreur, mais honnêtement, je ne sais pas comment j'aurais
fait, car les seules options que je vois c'est Enregistrer comme brouillon, Envoyer pour validation et
Dupliquer un événement.
J'ai créé tous les ateliers hier, en commençant par les premiers.
Je viens de les recréer et de les envoyer pour révision.

**Comment by saumier** [comment]
@troughc Is Maude still expecting feedback on this? It was opened over a month ago.

**Comment by troughc** [comment]
Yes. please investigate.

**Comment by saumier** [comment]
@dev-aravind Can you look into this old issue that is still important for us to answer?  If you can't find anything in the logs because it is too old then please report this back. Thx.

**Comment by dev-aravind** [comment]
@troughc @saumier The logs are not available as they are 2 old and I did not find any events with similar name as "canopée" created on April 30th. 

The only 2 events which had the word "canopée" in their name are:
[Event 1](https://cms.footlight.io/dashboard/63457978637093005071a053/events/665a2338beddbb00645e6452) (Obsolete, created on May 31st)

[Event 2](https://cms.footlight.io/dashboard/63457978637093005071a053/events/66461f7a9f43170063fa7fb7) (Published, created on May 16th)

**Comment by saumier** [comment]
obsolete, draft, in-review, publish - enums.

**Comment by troughc** [comment]
@MaudeFJ we did some investigation and we cannot find these events. So perhaps they did not save as expected. I am going to close this issue. If it happens again, please let us know.
