### ISSUE TITLE
Mobile display - contents don't fit in screen (not enough room)

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#63]
I just test creating a new event on my phone and the bigger menu are not the most pratical. Here's a walk tru 
https://crclaval-my.sharepoint.com/:f:/g/personal/m_fraser_culturelaval_ca/EmEK44KFs25HnGFVyQ_olsgBBvZgc0XF0F6lF4gin1Rbrg?e=Cjm6sW

**Caitlin's additional comments for this issue:**
Mobile phone: Iphone 12 mini on IOS 17.4.1
Browser: Safari
Main Issue: not enough space around open menus to scroll background; open menus don't completely fit in screen; top navigation menu doesn't appear to be sticky

**Comment by troughc** [comment]
@MaudeFJ Thank you for this.

First, can you please add the mobile phone brand and version you are using (so we can look at the dimensions). The UI fits in my mobile. 

Second, the top navigation (with the menu) is supposed to always be displayed at the top of the screen (it should be 'sticky'). Once I know what phone you are using we can test that. This navigation is always visible for me and on the phones we tested.

Third, that the keyboard automatically pops up: that's a known issue as it's a feature of mobile phones. 

Can you specify any other issues when you share your phone details?
thanks,
Caitlin

**Comment by MaudeFJ** [comment]
My phone is an Iphone 12 mini  on IOS 17.4.1, I was on safari.
It was mostly around having to scoll in the menu and in the page to see all the menu, and having almos no space left to tap outside of the menu to get out of it and keep scolling.
Thanks

**Comment by SyamBabu-M** [comment]
@troughc I am currently testing this in various phones. This is the link to the [PR](https://pr-1137.dla06mbe0wyl7.amplifyapp.com/) if you want to join the testing.

**Comment by troughc** [comment]
Tested on google and apple mobiles. Good to go!!! PASSED
