### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#65]
<img width="1880" alt="Capture d’écran, le 2024-05-29 à 08 40 28" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/f481fbae-db6a-4dc6-94d6-de882e7ad2eb">

**Comment by troughc** [comment]
@saumier do we need to get more information from Maude or is this screenshot enough?

**Comment by troughc** [comment]
@sahalali can you look into this based on the screenshot above.

**Comment by suhail-aliyar** [comment]
This is happened because the calendar id is not added correctly to the URL.
@SyamBabu-M / @AbhishekPAnil Can you please confirm if we have fixed this issue and not deployed to Production?

**Comment by MaudeFJ** [comment]
It's happening again 

https://github.com/culturecreates/tech-support-tickets/assets/135066077/d3b15d3f-f2e3-4c81-923e-bb7a8891c7ac

**Comment by troughc** [comment]
Thanks @MaudeFJ  we will look into this.
cc @saumier

**Comment by SyamBabu-M** [comment]
@troughc you can test it [here](https://pr-1147.dla06mbe0wyl7.amplifyapp.com/)

**Comment by troughc** [comment]
Tested: PASSED. This was happening when the user changed workspaces very quickly and the calendar ID came up as undefined. We added a safeguard. Please push to production

**Comment by troughc** [comment]
@MaudeFJ this has been fixed and deployed to production.
