### ISSUE TITLE
SignéLaval Events missing performer custom taxonomy

### ISSUE THREAD

**Issue by saumier** [culturecreates/tech-support-tickets#66]
The following Signé Laval event "Festival Feaster 2024" https://api.footlight.io/events/66058489140606006460b662 
has performers like "Le Ice" https://cms.footlight.io/dashboard/63457978637093005071a053/people/add-person?id=66197bcc14060600646b1d0f listed in the event performers, but are missing the "Lieu de travail"  taxonomy in the event details  response from the Open API.

Story: The developer at Folklore, Nicolas, needs to display only performers tagged as "Lavalois" in the front-end event details page.

Note this event is happening this weekend. 
Event on Signé Laval: https://signelaval.com/fr/evenements/66058489140606006460b662/festival-feaster-2024

In trying to trace the problem I noticed that Open API /people/UUID is also NOT returning the custom taxonomy "Lieu de travail".
https://api.footlight.io/people/66197bcc14060600646b1d0f

**Comment by suhail-aliyar** [comment]
@saumier The root cause of not returning dynamic field details in the person detail API response has been identified and fixed. This issue has now been hotfixed in production.

**Comment by saumier** [comment]
@sahalali I am not seeing the dynamic field yet https://api.footlight.io/events/66058489140606006460b662

**Comment by saumier** [comment]
This is working now https://api.footlight.io/events/66058489140606006460b662

Thanks @sahalali for the hot fix. The client is not working with their developer to add this on their website in time for the weekend :-)
