### ISSUE TITLE
I could not publish 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#7]
I click multiple time and nothing happend 
then i had 6 x the same event 
<img width="671" alt="Capture d’écran, le 2023-06-01 à 14 31 19" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/1572c0ff-77d5-460c-988b-79a91e8f83f8">
<img width="1149" alt="Capture d’écran, le 2023-06-01 à 14 30 06" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/fb0c0de7-1162-4cac-9c1e-a4215b14863d">

**Comment by troughc** [comment]
@AbhishekPAnil this looks like the same problem as issue #304 here: https://github.com/orgs/culturecreates/projects/2/views/1?filterQuery=304&pane=issue&itemId=26573939
let's prioritize this one.

**Comment by troughc** [comment]
@MaudeFJ just to update you: the fix for this issue is in progress. Should be completely resolved soon.
