### ISSUE TITLE
Bug - kaspersky blocking footlight

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#71]
Issue is that the CMS does not look like a trusted source, so she is blocked from joining.

![Capture 2](https://github.com/culturecreates/tech-support-tickets/assets/135066077/9894b421-1cc3-4a35-be12-a45d543d5058)
We have a user that can't access the cms because of this

**Comment by saumier** [comment]
@MaudeFJ  I don't recognize the url in the browser in the screen shot.

The url in the browser should be https://cms.footlight.io.

**Comment by MaudeFJ** [comment]
It was de URL of the invitation, but maybe Kapestry change URL ?

**Comment by saumier** [comment]
@MaudeFJ The only thing we can do is ask her to try again with our link https://cms.footlight.io/
