### ISSUE TITLE
Urgent *** BUG - all the obligatory boxes are filled but it keep saying it's missing something 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#73]
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6686c0309d0a290064babbfc
![Capture d’écran, le 2024-07-04 à 13 54 32](https://github.com/culturecreates/tech-support-tickets/assets/135066077/61eec759-ee31-4857-b043-98dd56e84ebb)

**Comment by MaudeFJ** [comment]
pouvez-vous le publier directement lorsque le problème sera réglé ?

**Comment by MaudeFJ** [comment]
Aussi discipline n'a plus son étoile alors que c'est obligatoire... 
![Capture d’écran, le 2024-07-04 à 16 07 28](https://github.com/culturecreates/tech-support-tickets/assets/135066077/7cee3fac-edc7-428c-aa5c-3a440c170133)

**Comment by MaudeFJ** [comment]
@saumier @troughc

**Comment by troughc** [comment]
@MaudeFJ this is a known bug we are working on. Thanks for letting me know you are experiencing it too.

**Comment by troughc** [comment]
@sahalali please let us know when this is resolved. 
@MaudeFJ can you try again?  I did a workaround by switching out your mandatory field for 'Disciplines' and was able to publish the event Club vidéo. (I then unpublished it).

**Comment by troughc** [comment]
Tested the issue that was causing this: PASSED. 
@MaudeFJ  we will also be fixing a related issue later today or tomorrow that affects changing mandatory fields. But this one shouldn't affect you as you are not changing your mandatory fields at this moment.
