### ISSUE TITLE
Bug Brouillon festival vivre ensemble as disapeared

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#75]
I have cescalar  user that saved its event "festival vivre ensemble" in brouillon yesterday PM, but it's not there. 
He created a new one but I'm still worried if things don't save properly. Do you see a trace of this somewhere ?

**Comment by troughc** [comment]
@MaudeFJ I found your user cescalar; however I did not find any events created by them in the CMS. I also didn't find an event called 'festival vivre ensemble'. I can confirm it doesn't exist for me either.

@sahalali can you look into whether the use named cescalar created and saved any events yesterday?

cc @saumier

**Comment by troughc** [comment]
Update on this event: I am now finding it in the CMS: https://cms.footlight.io/dashboard/63457978637093005071a053/events/66aa662e508ed10064fba5fb

I am not sure what happened between when we created this issue and now. thanks.

**Comment by MaudeFJ** [comment]
as stated he created a new one. but the first one should have been saved

**Comment by troughc** [comment]
Understood @MaudeFJ . A concern is that his recreated event wasn't visible when i checked earlier today. And now it is.

**Comment by MaudeFJ** [comment]
It's probably because he wasnt done when a flagged the issue


Maude Fraser

Responsable de Signé Laval  ​

450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3

C'est l'été! Veuillez noter que Culture Laval et Signé Laval seront fermés tous les vendredis entre le 1er juillet et le 30 août inclusivement.
  [cid:83d14c71-88a8-4b91-8dec-896fbe778b24]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.

________________________________
De : troughc ***@***.***>
Envoyé : 31 juillet 2024 15:50
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Bug Brouillon festival vivre ensemble as disapeared (Issue #75)


Understood @MaudeFJ<https://github.com/MaudeFJ> . A concern is that his recreated event wasn't visible when i checked earlier today. And now it is.

**Comment by suhail-aliyar** [comment]
I reviewed the logs and found that an event titled "Festival Vivre Ensemble" was created on July 31, 2024 at 12:28:30.680 PM EDT (9:58:30.680 PM IST). The event was updated three times during the day. Additionally, I noticed that the user created an organization called "Carnaval de Barranquilla en Canada" and updated the "ESCALAR" organization yesterday.

For Reference: https://app.datadoghq.com/logs?query=6675716f1180fb0064601d4f%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1722364200000&to_ts=1722494400000&live=false

**Comment by troughc** [comment]
@MaudeFJ unfortunately, we cannot debug this because there is no log evidence that your contributor created the event before the time you originally logged this issue. 
If it happens again, please let us know

**Comment by MaudeFJ** [comment]
So the theroy is that he never hit the save button ?

**Comment by troughc** [comment]
I think that it may be user error, yes. But I can't know for sure. Maybe he thought he hit the save button? Maybe he backed out of the event unintentionally...Or maybe it's a 'ghost in the machine'.
