### ISSUE TITLE
Tried to add an artist and after saving i had this message 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#76]
@sahalali Signe Laval admin tried to add an artist. After saving she got this error message (also when she went back to the event, she couldn't access the EVENT and still got that message)
<img width="719" alt="Capture d’écran, le 2024-07-31 à 10 22 19" src="https://github.com/user-attachments/assets/1e2c83c6-2dc6-4627-a9cb-9e28d89bc854">

Artist name: Boogat

Event name: Boogat | Mosaique à Centropolis

Here is a link to the event in the list view (which leads to an error if you click it: https://cms.footlight.io/dashboard/63457978637093005071a053/events?page=1&order=asc&sortBy=upcomingEventDate&query=bougat

Here is a link to the person (which works for me): https://cms.footlight.io/dashboard/63457978637093005071a053/people/66aa487c508ed10064fb9817

**Comment by troughc** [comment]
@MaudeFJ can you please give the name of the event and the name of the artist you tried to create.

**Comment by MaudeFJ** [comment]
Boogat
Boogat | Mosaique à Centropolis



Maude Fraser

Responsable de Signé Laval  ​

450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3

C'est l'été! Veuillez noter que Culture Laval et Signé Laval seront fermés tous les vendredis entre le 1er juillet et le 30 août inclusivement.
  [cid:2fb0f32a-46ae-4e3b-9f91-632152f790c6]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.

________________________________
De : troughc ***@***.***>
Envoyé : 31 juillet 2024 10:45
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Tried to add an artist and after saving i had this message (Issue #76)


@MaudeFJ<https://github.com/MaudeFJ> can you please give the name of the event and the name of the artist you tried to create.

**Comment by troughc** [comment]
@sahalali @MaudeFJ FYI: the event link is broken for me; the artist link works. I put them both in the description of this issue.

**Comment by suhail-aliyar** [comment]
The problem occurred because of a glitch in the backend, but it has been resolved now.

**Comment by troughc** [comment]
@MaudeFJ this issue has been fixed. Thanks.
