### ISSUE TITLE
I created an artist but can't associate a user to it 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#77]
Additional comments from Caitlin
Confirmed that a PERSON (artist) cannot be added to a user profile. Also confirmed that when you create any artist in any calendar, it cannot be added to the user profile. This is because the PERSON field is linked to Organizations instead of People, once you start typing in the search. 
Please investigate further.

Steps to reproduce
1. OPTIONAL: create an artist (person)
2. go into a user profile
3. When you first put your cursor in the field, you MAY see a list of people. However, when you start typing and try to add [this artist](https://cms.footlight.io/dashboard/63457978637093005071a053/people/66aa4974508ed10064fb9b00) to the calendar section:
<img width="628" alt="Capture d’écran, le 2024-08-01 à 10 15 44" src="https://github.com/user-attachments/assets/ed549fbf-5817-40c4-bfef-cc1489d13a69">
4. The artist is not available.
<img width="527" alt="Capture d’écran, le 2024-08-01 à 10 15 40" src="https://github.com/user-attachments/assets/15bc1f4a-1a76-4934-9f4a-56f01b0236b9">

5. In people field, search for an organization - you will find it.

Expected behavior: Person search field in user profile should link to people database.

**Comment by AbhishekPAnil** [comment]
Bug report :
As @troughc mentioned the Person search field was indeed look inside the organization database,thats why the empty search result showed.The search query is now corrected.

**Comment by troughc** [comment]
@MaudeFJ this is now fixed. Thanks for pointing it out!
