### ISSUE TITLE
Events read only view: "quartier" is missing from the Place component

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#79]
In the Read-only view, we display information about the address as a component.The 'Quartier' is missing from this Place component.  Please make sure that all the data that is displayed in the Edit view also appears in the Read-only view.
For an example, see [this event](https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66aa662e508ed10064fba5fb)
### Edit view:

<img width="780" alt="Screenshot 2024-08-13 at 1 20 08 PM" src="https://github.com/user-attachments/assets/1f2524a8-0051-4ce4-9a68-83700e652f49">

### Read only view missing the 'quartier'

<img width="652" alt="Screenshot 2024-08-13 at 1 19 58 PM" src="https://github.com/user-attachments/assets/65fad5ad-36b3-499d-b4d5-e7a7dead1aeb">

**Comment by SyamBabu-M** [comment]
@troughc Here is the link for testing https://pr-1284.dla06mbe0wyl7.amplifyapp.com/

**Comment by troughc** [comment]
Tested: PASSED
