### ISSUE TITLE
Publish an event and its not in the list 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#8]
I created an event and click publish, and this nowhere to be found ... 
It was called peinture 3d
<img width="1044" alt="Capture d’écran, le 2023-06-01 à 15 50 40" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/d805c163-acfa-40e0-9346-ab27359b0441">

**Comment by troughc** [comment]
@MaudeFJ Only events that are current and future events are listed by default (not past events). So I did a search for your event and found it in the past (see screenshot at bottom). The way you can find it is as follows:
Steps:
1. Click the dates filter and select the all dates option at the bottom (for this kind of task I prefer this option over the Past option.
2. Search for your event in the search field.
3. If the event exists in the database it will be displayed.
You're event is dated for May 21, 2023. 



<img width="1080" alt="Screenshot 2023-06-02 at 9 44 26 AM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/6c680f6f-1003-40cf-96cf-f3cb96c2d931">
