### ISSUE TITLE
I'm in a pickle for a show happening IN the river

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#81]
https://www.parc-mille-iles.qc.ca/activites/concert-au-crepuscule-par-emilis/
The location is indicated on the map on that website 
I can put a pinpoint on google map and get the coordinates, but there is no address or code postal so I cant save the "lieu" in the cms...

**Comment by troughc** [comment]
@MaudeFJ I created this: https://cms.footlight.io/dashboard/63457978637093005071a053/places/66ba0c11d09b4d006351a2ce

It's a test. What I did is a looked up the geo coordinates (they could be right or wrong) and then put them in the place. This is the google page where I got a postal code. 
https://www.google.com/maps/place/45%C2%B036'09.9%22N+73%C2%B049'01.9%22W/@45.602761,-73.817205,17z/data=!3m1!4b1!4m4!3m3!8m2!3d45.602761!4d-73.817205?entry=ttu

Then I also put the postal code int he address field. 
Please take a look and let me know if it helps solve your problem.

**Comment by MaudeFJ** [comment]
I created this on my part but does it respect the criteria 
: https://cms.footlight.io/dashboard/63457978637093005071a053/places/66ba07c3d09b4d006351a0e4

**Comment by MaudeFJ** [comment]
What i tried with only the coordonate in the front end the map was just in the middle of Laval

**Comment by troughc** [comment]
Hmm, I am not sure why it doesn't work. Can we have a quick call?

**Comment by troughc** [comment]
@MaudeFJ I just sent you an invite

**Comment by troughc** [comment]
@MaudeFJ it looks like it may be Google blocking this. You might have to ADD the place to google maps. I started looking into this, but it is outside my expertise. 

Gregory is back on Wednesday so we could check with him then.


What I tried is this: in Google maps, I place the pin drop, then I click 'Add a missing place' option. From there, you have to do a bit of digging to find the right kind of 'place' - yours doesn't exist from what i can see (you can't add River, you could add Park). 
<img width="420" alt="Screenshot 2024-08-12 at 9 48 25 AM" src="https://github.com/user-attachments/assets/33eae16d-0782-497b-a501-59d55c4ff121">

Let me know if you need to meet.

**Comment by troughc** [comment]
One more thing Maude. I looked at the satellite view of the map they are using on the other site and this is what I see:

<img width="890" alt="Screenshot 2024-08-12 at 12 30 06 PM" src="https://github.com/user-attachments/assets/5d6873d6-1427-413f-9875-129ef8e96191">

It's like its' a fake map? Looks odd to me.

**Comment by MaudeFJ** [comment]
I don't understand wath you meen by "fake map" ...

________________________________
De : troughc ***@***.***>
Envoyé : 12 août 2024 12:31
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] I'm in a pickle for a show happening IN the river (Issue #81)


One more thing Maude. I looked at the satellite view of the map they are using on the other site and this is what I see:

Screenshot.2024-08-12.at.12.30.06.PM.png (view on web)<https://github.com/user-attachments/assets/5d6873d6-1427-413f-9875-129ef8e96191>

It's like its' a fake map? Looks odd to me.

**Comment by troughc** [comment]
Never mind, LOL I think it's shallow...the satellite view doesn't look like the map view to me.

**Comment by MaudeFJ** [comment]
Maybe because those ARE shallow water haha like a  "bayou" So it looks like water in the map view but like grass in the satellite one..


Maude Fraser

Responsable de Signé Laval  ​

450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3

C'est l'été! Veuillez noter que Culture Laval et Signé Laval seront fermés tous les vendredis entre le 1er juillet et le 30 août inclusivement.
  [cid:90d31fd1-4b0c-4d5f-9ffd-9713db43dded]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.

________________________________
De : troughc ***@***.***>
Envoyé : 12 août 2024 12:37
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] I'm in a pickle for a show happening IN the river (Issue #81)


Never mind, LOL I think it's shallow...the satellite view doesn't look like the map view to me.

**Comment by troughc** [comment]
@MaudeFJ I have tried a few tests but have gotten nowhere. I will ask Gregory to take a look when he returns. I will also check with the tech team tomorrow.

**Comment by troughc** [comment]
Gregory, after you get back, let's discuss this issue with geocoordinates on maps please.

**Comment by saumier** [comment]
@MaudeFJ @troughc I believe the event started with a kayak ride from the quai located at 345, boulevard Sainte-Rose Laval QC H7L 1M7. So I would have put that address because that is where you can drive your car. If in the future some event has no street address then the place you created seems sufficient for now (until we add a new feature to remove street address for outdoor venues) with the understanding that the maps on the Signé Laval website may be using the postal address to display maps instead of the geo-coordinates. If that is the case, then the map would have to be changed to use geo-coordinates to show the right spot. Something to be checked with Folklore.

**Comment by saumier** [comment]
@troughc Let me know if you want to discuss more. The event has passed, but it may be work checking with Folklore why the map showed up in the center of Laval when Maude entered good geo-coordinates.

**Comment by troughc** [comment]
@saumier let's discuss this week.

**Comment by troughc** [comment]
@MaudeFJ we are closing this issue. But we are opening a separate one where we fix the problem with not being able to add geo-coordinates.

**Comment by troughc** [comment]
@MaudeFJ FYI, we fixed the geo-coordinates issue. Going forward, you should be able to add and save geo coordinates in places. Thanks.

**Comment by MaudeFJ** [comment]
> @MaudeFJ @troughc I believe the event started with a kayak ride from the quai located at 345, boulevard Sainte-Rose Laval QC H7L 1M7. So I would have put that address because that is where you can drive your car. If in the future some event has no street address then the place you created seems sufficient for now (until we add a new feature to remove street address for outdoor venues) with the understanding that the maps on the Signé Laval website may be using the postal address to display maps instead of the geo-coordinates. If that is the case, then the map would have to be changed to use geo-coordinates to show the right spot. Something to be checked with Folklore.

--> i understand the driving part  but people can also go in kayak to the location without passing by the 345 quai

**Comment by troughc** [comment]
Thanks for that info Maude, it helps with understanding.
