### ISSUE TITLE
Bug !! guest being super admin ..! and not being able to change the artiste associated too 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#88]
Bug: guest user has superadmin access.

I invited lucette yesterday i remember inviting her as a guest. But today I wanted to associate her artiste profile to her user profile and first I couldn't (maybe because she as not yet used the invitation ?)
But second, when I went back the the main page I saw this 
<img width="776" alt="Capture d’écran, le 2024-09-06 à 10 23 15" src="https://github.com/user-attachments/assets/a977257c-dc12-4eef-a6e8-9907f19ce20f">
This is a lot of access ...

**Comment by MaudeFJ** [comment]
It's the second time i saw it 
My collegue had invited some one over my vacation and she invited him as a guest and when I went in I saw superadmin as well

**Comment by troughc** [comment]
@MaudeFJ thanks for finding this bug.
Question: when you saw that she was a superadmin today, did you change her role back to guest or did it change on it's own? 
I also see that this Lucette is now associated with her artist profile. 
How did you manage to do that?

**Comment by troughc** [comment]
@sahalali, here is some additional info from the Signe Laval Admin:
When the guest user (who appeared to be a superadmin) accepted the invitation from Maude she had a bug (wasn't able to accept the invitation).
That is when the Admin went back to look at the profile. When she saw that she was a super admin, the admin put back to a guest role and I associated the artist profile.

email from the guest user to the admin:
 
From: artise@videotron.ca < artise@videotron.ca >
Sent: Friday, September 6, 2024 11:22:54 AM (UTC-05:00) Eastern Time (US & Canada)
To: Info Signed Laval < info@signelaval.com >
Subject: RE: Invitation to Signé Laval's Footlight calendar.

Hello Maude

It didn't work.

I think I needed to reset the password.

**I am being told that it is an error and not authorized.**

Lucette Tremblay


From: info@footlight.io < info@footlight.io >
Posted: September 5, 2024 5:11 PM
To: artise@videotron.ca
Subject: Invitation to the Footlight calendar by Signé Laval.

Signed Laval
Maude Fraser invites you to participate in the Signé Laval calendar.Signé Laval is powered by Footlight, a flexible way for users to list events that are easy to find and available for reuse. With Footlight, your events are structured to be discovered and shared and can be reused by the entire arts and culture community via Artsdata. You can also import events that have already been created to minimize repetitive data entry.

**Comment by suhail-aliyar** [comment]
This happened because the role was not in the database for that particular user. So the CMS defaulted to Super-Admin. The user's role disappears when updating the user before they accept the invitation(missing in the payload).
Steps to reproduce:
Invite a new user to the calendar
Go to their profile edit page and click save (before invitation is accepted)
The user role will now be displayed as Super Admin in the listing page

@AbhishekPAnil

**Comment by AbhishekPAnil** [comment]
Bug report :
The active calendars were only displayed when the user's status was set to ACTIVE. In this case, since the status was "Invited," the roles were not shown in the CMS and, as a result, were not included in the payload.

**Comment by AbhishekPAnil** [comment]
Deployed to production as a hotfix.

**Comment by troughc** [comment]
Looks good @AbhishekPAnil I see no issues. Thank you!

**Comment by troughc** [comment]
@MaudeFJ  this issue is fixed and should not happen again. And the user never had access to any extra data, even though it looked like they were a super admin. We tested that to make sure. 
thanks for finding it for us!

**Comment by MaudeFJ** [comment]
Super !
