### ISSUE TITLE
Urgent: Signe Laval cannot publish an upcoming event that has all mandatory fields.

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#89]
<img width="517" alt="Capture d’écran, le 2024-09-16 à 16 36 53" src="https://github.com/user-attachments/assets/9a68cf3d-ac66-4659-ac08-b6ee19a3a914">
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66e6ef83cc25ad00631e63ea
It dosnt highlight the problem neither. 
The event is soon could we correct this quickly ? Thanks

**Comment by troughc** [comment]
@sahalali @AbhishekPAnil when I look at this issue, I think it may be the fact that the location is a virtual location, not a place. But this should NOT block the event from being published. Please check what is blocking this event from being pubished and fix? Thank you.

Also note that the problematic field is NOT indicated in the form. Please check this as well.

**Comment by dev-aravind** [comment]
@troughc This is now hotfixed into production. The event mentioned above should be publishable now.

**Comment by troughc** [comment]
Tested: PASSED.

**Comment by troughc** [comment]
@MaudeFJ Please go ahead and publish the event now. The issue has been fixed.

**Comment by MaudeFJ** [comment]
Thansk !

________________________________
De : troughc ***@***.***>
Envoyé : 18 septembre 2024 09:10
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Urgent: Signe Laval cannot publish an upcoming event that has all mandatory fields. (Issue #89)


@MaudeFJ<https://github.com/MaudeFJ> Please go ahead and publish the event now. The issue has been fixed.
