### ISSUE TITLE
mobile issue: when entering a time for dates

### ISSUE THREAD

**Issue by troughc** [culturecreates/tech-support-tickets#9]
A user should be able to enter a time for a date WITHOUT having to:

-  touch OK on a mobile device / touch screen- standard way it works on phones.
-

**Comment by troughc** [comment]
@saumier this issue was raised by tout culture and I wouldl ike to add it to the the support tickets but I can't figure out how to do that. can you help me out?

**Comment by troughc** [comment]
For testing: test usage of the dropdown and click outside ; test usage of fully entering the time and click outside. This should work

**Comment by troughc** [comment]
Tested staging on mobile and desktop - what is described above works.
One issue: when you touch in the field on the phone and then try to scroll the dropdown with the first touch, it doesn't work. Instead it scrolls the page. After you touch the dropdown once, it then scrolls. Is there a way to put the focus on the dropdown so the interaction is more seamless @SyamBabu-M ?

**Comment by SyamBabu-M** [comment]
@troughc Sure. I will make the dropdown focus automatically once the dropdown is opened.

**Comment by SyamBabu-M** [comment]
@troughc I did the additional change you mentioned yesterday. Now in mobile screens, when a date is selected, the keyboard will close immediately. Please check if everything is alright.

**Comment by troughc** [comment]
Tested on my phone (pixel 6): PASSED.
