### ISSUE TITLE
Aggregator for Ville de Laval creating a duplicate for all the place. 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#91]
Example event: https://cms.footlight.io/dashboard/63457978637093005071a053/events/66da98c4345131006449a542
The place for this event (which was added by the ville de laval aggregator) is already in the Footlight CMS database.  A new one is being added instead of linking to the one with all the info and surtout Quartier ! 

Place that was added (and is linked to many events and to Artsdata): https://cms.footlight.io/dashboard/63457978637093005071a053/places/66cd889d345131006442c1f5

PLace that already existed in CMS (Only linked to one event): https://cms.footlight.io/dashboard/63457978637093005071a053/places/6441397b7a29930064509bc8

**Comment by troughc** [comment]
@saumier FYI in case there is something to do in Artsdata.

**Comment by troughc** [comment]
@sahalali is this one resolved?

**Comment by suhail-aliyar** [comment]
@sahalali to see if any place with Artsdata ID is duplicating while running aggregator.

**Comment by dev-aravind** [comment]
@sahalali @troughc This happened during a [buggy run](https://github.com/culturecreates/footlight-aggregator/actions/runs/11493944683) of the aggregator import for Ville de Laval. This was fixed on the same day, and I have removed the [duplicate places](https://docs.google.com/spreadsheets/d/19h9pD2yDmOE9TcIlBtKNt4ge6YoDH55i6j1fBawNQv0/edit?gid=338345520#gid=338345520) that were created.

**Comment by troughc** [comment]
@dev-aravind for[ this event ](https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66da98c4345131006449a542)that was mentioned in the top description: it is a past event but it no longer has a location. 
for the list of locations that you deleted - were there any events where they were used? If yes, do those events have their locations intact?

**Comment by troughc** [comment]
Tested: PASSED
