### ISSUE TITLE
Event Film Seuils... not showing on Signé Laval website

### ISSUE THREAD

**Issue by saumier** [culturecreates/tech-support-tickets#96]
The event in CMS called `Film Seuils disponible! Une production du Théâtre Incliné de Laval`  https://cms.footlight.io/dashboard/63457978637093005071a053/events/66fef0c248f4030063f322ba is not showing up on the Signé Laval website, event though it should be.

**Comment by troughc** [comment]
@saumier do you know why it isn't showing up? Is it because it is an online event? When I search on Signe Laval for online events, there were no results: https://signelaval.com/fr/evenements?types[]=online

**Comment by troughc** [comment]
@saumier I checked with Maude and she said she knows about it and that she is working with Folklore to solve this issue. Looks like it's on their side. Please feel free to close this if you think this resolves your question.
