### ISSUE TITLE
Nice to have : moving the tag around in the field

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#97]
Since the first tag of the discipline have a different treatment in the front end, I would like to move some discipline up to the front of the list but now I cant I have to delete everything and start over. 
that would be a nice to have ! Thanks

**Comment by troughc** [comment]
Hi @MaudeFJ do you mean that you would like to elevate some of the nested controlled vocabulary for discipline? As in, you would like them to be at the top level? For example are you asking to move to something like 'Dessin' to be at the  same level as 'Arts visuels' like this?
<img width="847" alt="Screenshot 2024-10-28 at 9 46 51 AM" src="https://github.com/user-attachments/assets/93dbccfd-7018-4bf0-a8ac-62868b334103">

You can already do that by dragging it out and dropping it into the list between two other top-level disciplines (and then move it to where you want). Or are you asking for something else?

**Comment by MaudeFJ** [comment]
<img width="907" alt="Capture d’écran, le 2024-10-28 à 09 55 12" src="https://github.com/user-attachments/assets/d306f9f5-7611-4787-bae0-2a6f1793f63a">

No I mean in an event...

**Comment by troughc** [comment]
So you mean you want to drag them to change the order inside the field.

**Comment by MaudeFJ** [comment]
oui!

**Comment by troughc** [comment]
@MaudeFJ we have released this feature. You can now change your taxonomy order directly in the field by dragging the bubbles around.

Note: in this first release you aren't warned to save the event (or any entity). So please remember to save the event if you change the order in the field. (we will add the 'remember to save' warning in a future release)

I will close this issue now. :)

**Comment by MaudeFJ** [comment]
Verry cool!!! Can't wait to try
