### ISSUE TITLE
bug : error while editing a place

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#99]
This error is related to error #100 
Maude was validating the "Mosaico" event and noticed that the location didn't have a neighborhood tag (#100 ) 
She clicked the edit button for the Place and got an error. 
- The name of broken Place in this event is "Salle Anaïs-Allard-Rousseau." It is minted and linked to Artsdata [here](https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK2-196)
- This is the link to the broken [Place in CMS](https://cms.footlight.io/dashboard/63457978637093005071a053/places/add-place?id=671fc4e6017105006374409d). This is what generates the error page.
- Note that Maude created a duplicate place with the same name [here](https://cms.footlight.io/dashboard/63457978637093005071a053/places/6728eed7cd5188006374d2f0) in order to make the event work. This place is NOT linked to Artsdata (not minted).

<img width="1735" alt="Capture d’écran, le 2024-11-04 à 10 49 15" src="https://github.com/user-attachments/assets/38a6db56-45e0-43d3-aca5-9fc463909785">

**Comment by troughc** [comment]
@MaudeFJ can you please give a bit more info on what happened before you got this error?

**Comment by MaudeFJ** [comment]
J'étais en train de valider l'événement Mosaico puis je voyais que le lieu n'avais pas de tag quartier (voir l'autre bug) donc j'ai cliqué sur éditer et j'ai eu l'erreur.



Maude Fraser

Responsable de Signé Laval  ​

450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3
  [cid:80bcf9da-b44e-4992-864d-3d18e9cb2164]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Twitter<https://twitter.com/Signe_Laval>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.

________________________________
De : troughc ***@***.***>
Envoyé : 4 novembre 2024 16:02
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] bug : error while editing a place (Issue #99)


@MaudeFJ<https://github.com/MaudeFJ> can you please give a bit more info on what happened before you got this error?

**Comment by troughc** [comment]
@MaudeFJ the link to the original place (linked to Artsdata) is no longer broken. This means you have two places of the same name in your CMS (duplicates). You can go ahead and delete one of them. 

Note that the one you recently created (that is NOT linked to Artsdata) is used for the "Mosaico" event. If you choose to delete that one, you will then have to update your location for the event. 
Also note that i have linked the two places in Artsdata so it doesn't matter which one you delete.

**Comment by troughc** [comment]
Tested: PASSED
@sahalali it looks like you already deployed this in production?
